apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-cd-pipeline-run-
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: git-url
      value: "https://github.com/johannfranzero/ci-cd-final-project.git"
    - name: git-revision
      value: "main"
    - name: app-name
      value: "cicd-app"
    - name: build-image
      value: "image-registry.openshift-image-registry.svc:5000/sn-labs-u423005320/cicd-app:latest"
